version: "3"
services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
  api:
    build: .
    ports:
      - "80:80"
    environment:
      - CURRENT_ENV=dev